# Use the official Redis image (version 7.4-alpine)
FROM redis:7.4-alpine

# Expose the default Redis port
EXPOSE 6379

# Default command to run when starting the container (no custom configuration needed)
CMD ["redis-server"]