kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-deployment
  namespace: tutorial
  labels:
    app: api
  annotations:
    config-update: "v1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: myUsername/myApi:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: api-configmap
          env:
            - name: REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: db-user-secretkey
                  key: REDIS_USER
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-pass-secretkey
                  key: REDIS_PASSWORD
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "64Mi"
