kind: Service
apiVersion: v1
metadata:
  name: api-service
  namespace: tutorial
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 80 # Puerto en el que el Service escucha dentro del clúster
      targetPort: 80 # Puerto en el contenedor al que se dirige el tráfico
      nodePort: 30900 # Puerto en cada nodo del clúster para acceder al Service externamente
